### ISSUE TITLE
Sydney freezes.

### ISSUE THREAD

**Issue by DinuNuggets** [WAppAI/assistant#119]
Sydney sometimes freezes. Then she can't process requests or output anything in the terminal. I don't know what the reason is, but it happens.

**Comment by Luisotee** [comment]
I have also noticed it, problem is I cant consistenly replicate it so it's hard to fix

**Comment by Ryzitos** [comment]
> Sydney sometimes freezes. Then she can't process requests or output anything in the terminal. I don't know what the reason is, but it happens.

I also have this problem sometimes

**Comment by Ryzitos** [comment]
> Sydney sometimes freezes. Then she can't process requests or output anything in the terminal. I don't know what the reason is, but it happens.

I also have this problem sometimes

**Comment by Luisotee** [comment]
I am working on creating a way to do a reset command in whatsapp to make it easier to restart her when it happens. It's hard to fix it since I can't find a way to consistently repeat it but I think the problem comes from the bing api we use ([waylaidwanderer/node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api)) where after the answer is done bing freeze and doesn't send the answer.
