### ISSUE TITLE
When using openrouter without searchapi key it's still trying to use it causing a loop.

### ISSUE THREAD

**Issue by Abdalnablse10** [WAppAI/assistant#269]
I did the following:

!change nousresearch/nous-capybara-7b

Successfully changed

I said : Hello

Normal response as expected.

Simple question : what's your name?

it started thinking about "London" and stuff then hopelessly tried to search over and over causing a loop.

**Comment by Luisotee** [comment]
The code currently still thinks it can use searchApi even without a proper key, in the next update I should fix that.

Now the problem you are getting is more related to the model being dumb and not understanding your question, this I cant fix since some models are too confused by the prompt we send it.
